# This file auto-generated by build_ui.sh. Don't edit.
__all__ = [
 "main",
 "mp3dialog",
 "preferences",
 "translate",
]
from . import main
from . import mp3dialog
from . import preferences
from . import translate
