# This file auto-generated by build_ui.sh. Don't edit.
__all__ = [
 "audiodialog",
 "copydialog",
 "download",
 "main",
 "preferences",
 "sortdialog",
 "textdialog",
 "translate",
]
from . import audiodialog
from . import copydialog
from . import download
from . import main
from . import preferences
from . import sortdialog
from . import textdialog
from . import translate
