# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audiodialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioDialog(object):
    def setupUi(self, AudioDialog):
        AudioDialog.setObjectName("AudioDialog")
        AudioDialog.resize(555, 650)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AudioDialog)
        self.verticalLayout_2.setContentsMargins(9, -1, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(AudioDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.settingBtn = QtWidgets.QPushButton(AudioDialog)
        self.settingBtn.setAutoDefault(False)
        self.settingBtn.setObjectName("settingBtn")
        self.horizontalLayout_4.addWidget(self.settingBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lrcCheck = QtWidgets.QCheckBox(AudioDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lrcCheck.sizePolicy().hasHeightForWidth())
        self.lrcCheck.setSizePolicy(sizePolicy)
        self.lrcCheck.setChecked(True)
        self.lrcCheck.setObjectName("lrcCheck")
        self.horizontalLayout_9.addWidget(self.lrcCheck)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(AudioDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.flowAdd = QtWidgets.QToolButton(AudioDialog)
        self.flowAdd.setObjectName("flowAdd")
        self.horizontalLayout_7.addWidget(self.flowAdd)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.bulkaddBtn = QtWidgets.QPushButton(AudioDialog)
        self.bulkaddBtn.setObjectName("bulkaddBtn")
        self.horizontalLayout_7.addWidget(self.bulkaddBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_1.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(AudioDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_1.addWidget(self.line_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(AudioDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_6 = QtWidgets.QLabel(AudioDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.pieceSpin = QtWidgets.QSpinBox(AudioDialog)
        self.pieceSpin.setProperty("value", 1)
        self.pieceSpin.setObjectName("pieceSpin")
        self.horizontalLayout_6.addWidget(self.pieceSpin)
        self.label_8 = QtWidgets.QLabel(AudioDialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.allBtn = QtWidgets.QRadioButton(AudioDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allBtn.sizePolicy().hasHeightForWidth())
        self.allBtn.setSizePolicy(sizePolicy)
        self.allBtn.setChecked(True)
        self.allBtn.setObjectName("allBtn")
        self.verticalLayout_5.addWidget(self.allBtn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.partBtn = QtWidgets.QRadioButton(AudioDialog)
        self.partBtn.setObjectName("partBtn")
        self.horizontalLayout_2.addWidget(self.partBtn)
        self.fromSpin = QtWidgets.QSpinBox(AudioDialog)
        self.fromSpin.setMinimum(1)
        self.fromSpin.setMaximum(99999)
        self.fromSpin.setProperty("value", 1)
        self.fromSpin.setObjectName("fromSpin")
        self.horizontalLayout_2.addWidget(self.fromSpin)
        self.label = QtWidgets.QLabel(AudioDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.toSpin = QtWidgets.QSpinBox(AudioDialog)
        self.toSpin.setMinimum(1)
        self.toSpin.setMaximum(99999)
        self.toSpin.setProperty("value", 1)
        self.toSpin.setObjectName("toSpin")
        self.horizontalLayout_2.addWidget(self.toSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_1.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.flowList = QtWidgets.QListWidget(AudioDialog)
        self.flowList.setStyleSheet("QListWidget::item { background: rgb(180, 180, 180); }")
        self.flowList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.flowList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.flowList.setObjectName("flowList")
        self.verticalLayout_3.addWidget(self.flowList)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(AudioDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.bgmAdd = QtWidgets.QToolButton(AudioDialog)
        self.bgmAdd.setObjectName("bgmAdd")
        self.horizontalLayout_8.addWidget(self.bgmAdd)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.bgmList = QtWidgets.QListWidget(AudioDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bgmList.sizePolicy().hasHeightForWidth())
        self.bgmList.setSizePolicy(sizePolicy)
        self.bgmList.setStyleSheet("QListWidget::item { background: rgb(150, 150, 150); }")
        self.bgmList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.bgmList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.bgmList.setObjectName("bgmList")
        self.verticalLayout_3.addWidget(self.bgmList)
        self.line = QtWidgets.QFrame(AudioDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(AudioDialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.pgMsg = QtWidgets.QLabel(AudioDialog)
        self.pgMsg.setText("")
        self.pgMsg.setObjectName("pgMsg")
        self.horizontalLayout.addWidget(self.pgMsg)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(AudioDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.stopBtn = QtWidgets.QPushButton(AudioDialog)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_5.addWidget(self.stopBtn)
        self.createBtn = QtWidgets.QPushButton(AudioDialog)
        self.createBtn.setCheckable(False)
        self.createBtn.setAutoDefault(False)
        self.createBtn.setDefault(False)
        self.createBtn.setObjectName("createBtn")
        self.horizontalLayout_5.addWidget(self.createBtn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AudioDialog)
        QtCore.QMetaObject.connectSlotsByName(AudioDialog)

    def retranslateUi(self, AudioDialog):
        _translate = QtCore.QCoreApplication.translate
        AudioDialog.setWindowTitle(_translate("AudioDialog", "Audio Setting"))
        self.label_4.setText(_translate("AudioDialog", "Text-to-Speech Service:"))
        self.settingBtn.setText(_translate("AudioDialog", "Setting"))
        self.lrcCheck.setText(_translate("AudioDialog", "Create Lyrics file"))
        self.label_2.setText(_translate("AudioDialog", "<html><head/><body><p>Audio Flow</p></body></html>"))
        self.flowAdd.setText(_translate("AudioDialog", "Add Item"))
        self.bulkaddBtn.setText(_translate("AudioDialog", "Bulk Add"))
        self.label_5.setText(_translate("AudioDialog", "Entries:"))
        self.label_6.setText(_translate("AudioDialog", "Output"))
        self.label_8.setText(_translate("AudioDialog", "files"))
        self.allBtn.setText(_translate("AudioDialog", "All"))
        self.partBtn.setText(_translate("AudioDialog", "From:"))
        self.label.setText(_translate("AudioDialog", "to:"))
        self.label_3.setText(_translate("AudioDialog", "BGM Loop"))
        self.bgmAdd.setText(_translate("AudioDialog", "Add Item"))
        self.label_7.setText(_translate("AudioDialog", "Progress:"))
        self.stopBtn.setText(_translate("AudioDialog", "Stop"))
        self.createBtn.setText(_translate("AudioDialog", "Create Audiobook"))
