# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/audiodialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AudioDialog(object):
    def setupUi(self, AudioDialog):
        AudioDialog.setObjectName("AudioDialog")
        AudioDialog.resize(507, 653)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AudioDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(AudioDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.settingBtn = QtWidgets.QPushButton(AudioDialog)
        self.settingBtn.setObjectName("settingBtn")
        self.horizontalLayout_2.addWidget(self.settingBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(AudioDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.wordSpin = QtWidgets.QSpinBox(AudioDialog)
        self.wordSpin.setMinimum(1)
        self.wordSpin.setProperty("value", 3)
        self.wordSpin.setObjectName("wordSpin")
        self.horizontalLayout_4.addWidget(self.wordSpin)
        self.label_6 = QtWidgets.QLabel(AudioDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lrcCheck = QtWidgets.QCheckBox(AudioDialog)
        self.lrcCheck.setChecked(True)
        self.lrcCheck.setObjectName("lrcCheck")
        self.horizontalLayout_6.addWidget(self.lrcCheck)
        self.idxCheck = QtWidgets.QCheckBox(AudioDialog)
        self.idxCheck.setChecked(True)
        self.idxCheck.setObjectName("idxCheck")
        self.horizontalLayout_6.addWidget(self.idxCheck)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(AudioDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.sfxList = QtWidgets.QListWidget(AudioDialog)
        self.sfxList.setStyleSheet("QListWidget::item { border-bottom: 1px solid black; }\n"
"QListWidget::item { background-color: rgb(211,208,204);}")
        self.sfxList.setObjectName("sfxList")
        self.verticalLayout_3.addWidget(self.sfxList)
        self.label_3 = QtWidgets.QLabel(AudioDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.bgmList = QtWidgets.QListWidget(AudioDialog)
        self.bgmList.setStyleSheet("QListWidget::item { border-bottom: 1px solid black; }\n"
"QListWidget::item { background-color: rgb(211,208,204); }")
        self.bgmList.setObjectName("bgmList")
        self.verticalLayout_3.addWidget(self.bgmList)
        self.line = QtWidgets.QFrame(AudioDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(AudioDialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.pgMsg = QtWidgets.QLabel(AudioDialog)
        self.pgMsg.setText("")
        self.pgMsg.setObjectName("pgMsg")
        self.horizontalLayout.addWidget(self.pgMsg)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(AudioDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.stopBtn = QtWidgets.QPushButton(AudioDialog)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_5.addWidget(self.stopBtn)
        self.createBtn = QtWidgets.QPushButton(AudioDialog)
        self.createBtn.setCheckable(False)
        self.createBtn.setAutoDefault(False)
        self.createBtn.setDefault(True)
        self.createBtn.setObjectName("createBtn")
        self.horizontalLayout_5.addWidget(self.createBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AudioDialog)
        QtCore.QMetaObject.connectSlotsByName(AudioDialog)

    def retranslateUi(self, AudioDialog):
        _translate = QtCore.QCoreApplication.translate
        AudioDialog.setWindowTitle(_translate("AudioDialog", "Audio Setting"))
        self.label.setText(_translate("AudioDialog", "TTS"))
        self.settingBtn.setText(_translate("AudioDialog", "Setting"))
        self.label_5.setText(_translate("AudioDialog", "Repeat word"))
        self.label_6.setText(_translate("AudioDialog", "times"))
        self.lrcCheck.setText(_translate("AudioDialog", "Create Lyrics file"))
        self.idxCheck.setText(_translate("AudioDialog", "Read index"))
        self.label_2.setText(_translate("AudioDialog", "Sound effects"))
        self.label_3.setText(_translate("AudioDialog", "BGM Loop"))
        self.label_7.setText(_translate("AudioDialog", "Progress:"))
        self.stopBtn.setText(_translate("AudioDialog", "Stop"))
        self.createBtn.setText(_translate("AudioDialog", "Start"))

