# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/mp3dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mp3Dialog(object):
    def setupUi(self, Mp3Dialog):
        Mp3Dialog.setObjectName("Mp3Dialog")
        Mp3Dialog.resize(472, 501)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Mp3Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Mp3Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ttsCombo = QtWidgets.QComboBox(Mp3Dialog)
        self.ttsCombo.setObjectName("ttsCombo")
        self.ttsCombo.addItem("")
        self.ttsCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.ttsCombo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Mp3Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.wordSpin = QtWidgets.QSpinBox(Mp3Dialog)
        self.wordSpin.setMinimum(1)
        self.wordSpin.setProperty("value", 3)
        self.wordSpin.setObjectName("wordSpin")
        self.horizontalLayout_4.addWidget(self.wordSpin)
        self.label_6 = QtWidgets.QLabel(Mp3Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gstaticCheck = QtWidgets.QCheckBox(Mp3Dialog)
        self.gstaticCheck.setChecked(True)
        self.gstaticCheck.setObjectName("gstaticCheck")
        self.verticalLayout.addWidget(self.gstaticCheck)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Mp3Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.sfxTree = QtWidgets.QTreeWidget(Mp3Dialog)
        self.sfxTree.setObjectName("sfxTree")
        self.verticalLayout_3.addWidget(self.sfxTree)
        self.label_4 = QtWidgets.QLabel(Mp3Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(Mp3Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.bgmList = QtWidgets.QListWidget(Mp3Dialog)
        self.bgmList.setObjectName("bgmList")
        self.verticalLayout_3.addWidget(self.bgmList)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.addBgmBtn = QtWidgets.QPushButton(Mp3Dialog)
        self.addBgmBtn.setObjectName("addBgmBtn")
        self.horizontalLayout_7.addWidget(self.addBgmBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.cancelBtn = QtWidgets.QPushButton(Mp3Dialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_5.addWidget(self.cancelBtn)
        self.createBtn = QtWidgets.QPushButton(Mp3Dialog)
        self.createBtn.setCheckable(False)
        self.createBtn.setAutoDefault(False)
        self.createBtn.setDefault(True)
        self.createBtn.setObjectName("createBtn")
        self.horizontalLayout_5.addWidget(self.createBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Mp3Dialog)
        QtCore.QMetaObject.connectSlotsByName(Mp3Dialog)

    def retranslateUi(self, Mp3Dialog):
        _translate = QtCore.QCoreApplication.translate
        Mp3Dialog.setWindowTitle(_translate("Mp3Dialog", "Audio Setting"))
        self.label.setText(_translate("Mp3Dialog", "TTS"))
        self.ttsCombo.setItemText(0, _translate("Mp3Dialog", "say"))
        self.ttsCombo.setItemText(1, _translate("Mp3Dialog", "espeak"))
        self.label_5.setText(_translate("Mp3Dialog", "Repeat word"))
        self.label_6.setText(_translate("Mp3Dialog", "times"))
        self.gstaticCheck.setText(_translate("Mp3Dialog", "Download nice pronunciation"))
        self.label_2.setText(_translate("Mp3Dialog", "Sound effects"))
        self.sfxTree.headerItem().setText(0, _translate("Mp3Dialog", "Group"))
        self.sfxTree.headerItem().setText(1, _translate("Mp3Dialog", "Name"))
        self.sfxTree.headerItem().setText(2, _translate("Mp3Dialog", "Duration"))
        self.label_4.setText(_translate("Mp3Dialog", ">>> Preview Coming <<<"))
        self.label_3.setText(_translate("Mp3Dialog", "BGM Loop"))
        self.addBgmBtn.setText(_translate("Mp3Dialog", "Add"))
        self.cancelBtn.setText(_translate("Mp3Dialog", "Cancel"))
        self.createBtn.setText(_translate("Mp3Dialog", "Create MP3"))

